library(shiny)

shinyUI(navbarPage("Chance of Rain",
    
   tabPanel(
       "Documentation",
       h2("Chance of Rain"),
       p(
           "Course project for ",
           tags$a(href = "https://www.coursera.org/learn/data-products", target="_blank", "Developing Data Products"),
           br(),
           "by ",
           tags$a(href = "https://www.linkedin.com/in/dimick/", target="_blank", "Seth Dimick")
       ),
       h3("Background"),
       p(
           "In Seattle, rain is something you learn to live with. I am no weather expert, but for this course project I decided to build a few simplistic models for predicting rainy days in Seattle based on historic data. This ",
           tags$a(href = "https://shiny.rstudio.com/", target="_blank", "Shiny"),
           " app is powered by 100 years (1918 to 2017) of weather data from the ",
           tags$a(href = "https://www.ncdc.noaa.gov/cdo-web/", target="_blank", "National Centers for Environmental Information"),
           " for the Portage Bay station in Seattle. The historic data is used to train a Logistic Regression model to predict the probability or rain as well as a GLM Classifier for rain versus no rain for a day given the month and whether or not on the previous day."
        ),
       p("Flip over to the \"App\" tab to check out the finished product!"),
       h3("How to Use the App"),
       h5("User Input"),
       tags$ul(
           tags$li("Select what month it is"),
           tags$li("Select if it has rained today")
       ),
       h5("Interpret Results"),
       tags$ul(
           tags$li("Headline generated by GLM Classification model for rain versus no rain"),
           tags$li("Probability of rain generated by Logistic Regression model"),
           tags$li("A visual of the historic data is generated for tomorrow's precipitation status for the selected month and status of today's precipitation")
       )
   ),
                   
   tabPanel(
        "App",
        h2("Will it Rain in Seattle Tomorrow?"),
        br(),
        fluidRow(
            column(3,
                wellPanel(
                    selectInput(
                        inputId = "month",
                        label = "Select Month",
                        choices = as.list(month.name[1:12])
                    ),
                    radioButtons(
                        inputId = "prevRain",
                        label = "Did it Rain Today?",
                        choices = list(Yes = 1, No = 0)
                    )
                )
            ),
            column(9,
                h3(textOutput("rain")),
                br(),
                h4("Probability of Rain Tomorrow"),
                plotOutput("probPlot", height = "100px"),
                h4(textOutput("histTitle")),
                plotOutput("histPlot")
            )
        )
    )
    
))